version: "3.9"
services:
    php-server:
        build: "./backend/server"
        ports:
            - "8080:80"
        volumes:
            - "./backend/server:/var/www/html"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - mysql-db
    mysql-db:
        image: mysql:5.7.16
        ports:
            - 3306:3306
        command:
            [
                "--default-authentication-plugin=mysql_native_password",
                "--explicit_defaults_for_timestamp=true"
            ]
        volumes:
            - ./backend/database/.mysql_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=27112021
    node-webserver:
        build:
            context: "./frontend"
            target: development
        container_name: node-webserver
        ports:
            - "3000:3000"
        volumes:
            - "./frontend/src:/app/src"
        depends_on:
            - mysql-db
            - php-server
